[build]
  publish = "_site"
  command = """
    curl -fsSL https://deno.land/x/install/install.sh | sh && \
    /opt/buildhome/.deno/bin/deno task build --location=https://mx.sb/ \
  """
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, age=120"
[[headers]]
  for = "*.js, *.css"
  [headers.values]
    cache-control = "public, age=86400"
[[headers]]
  for = "/pagefind/*"
  [headers.values]
    cache-control = "public, age=604800"
[[redirects]]
  from = "/cv"
  to = "https://publish.uwo.ca/~jding263/resume"
  status = 303
